on:
  push:

jobs:
  define-matrix:
    name: Define allowed cities
    runs-on: ubuntu-latest

    outputs:
      cities: ${{ steps.extractor.outputs.cities }}

    steps:
      - name: Checkout config
        uses: actions/checkout@v4
      - name: Extract cities
        id: extractor
        run: |
          echo "cities=$(jq -cS '[.defaults as $defaults | .cities[] | ($defaults + .)] | .[] | select(.weekday | contains(\"$(date -d '+2day' +%A)\"))' config.json)"
