on:
  push:

jobs:
  define-matrix:
    name: Define allowed cities
    runs-on: ubuntu-latest

    outputs:
      cities: ${{ steps.extractor.outputs.cities }}

    steps:
      - name: Checkout config
        uses: actions/checkout@v4
      - name: Extract cities
        id: extractor
        run: |
          JQ_ACTIONS="[.defaults as $defaults | .cities[] | ($defaults + .)]"               # Merge defaults with each city
          JQ_ACTIONS+=" | .[] | select(.weekday | contains(\"$(date -d '+2day' +%A)\"))"   # Filter by weekday
          echo "cities=$(jq -cS --arg JQ_ACTIONS '$JQ_ACTIONS' '$JQ_ACTIONS' config.json)"
