on:
  push:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      cities: ${{ steps.extractor.outputs.cities }}

    steps:
      - name: Checkout config
        uses: actions/checkout@v4
      - name: Extract cities
        id: extractor
        run: |
          echo "cities=$(jq -cS '[.defaults as $defaults | .cities[] | ($defaults + .)]' config.json)" >> "$GITHUB_OUTPUT"

  announce-hangout:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        city: ${{ fromJSON(needs.define-matrix.outputs.cities) }}

    steps:
      - name: Announce Hangout
        env:
          CHAT_ID_VAR: ${{ format('{0}_CHAT_ID', matrix.city.name) }}
          TZ: ${{ matrix.city.timezone }}
        run: |
          echo "City: ${{ matrix.city.name }}"
          echo "Chat ID: $$CHAT_ID_VAR"
