on:
  push:

jobs:
  define-matrix:
    name: Define allowed cities
    runs-on: ubuntu-latest

    outputs:
      cities: ${{ steps.extractor.outputs.cities }}

    steps:
      - name: Checkout config
        uses: actions/checkout@v4
      - name: Extract cities
        id: extractor
        run: |
          WEEKDAY=$(date -d '+2day' +%A)
          echo "cities=$(jq -cS --arg WEEKDAY "$WEEKDAY" '
                  [.defaults as $defaults | .cities[] | ($defaults + .)]
                  | .[] | select(.weekday | contains($WEEKDAY))
                ' config.json)"
