on:
  workflow_call:

jobs:
  validate-config:
    name: Validate config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config
        uses: actions/checkout@v4
      - name: Validate JSON
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'config.json'
